CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE_NUMBER VARCHAR(15),
    CITY VARCHAR(50),
    CREATED_DATE DATE
);


INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, CITY, CREATED_DATE)
VALUES (1, 'Amit', 'Sharma', 'amit.sharma@example.com', '9876543210', 'Delhi', TO_DATE('2023-06-01', 'YYYY-MM-DD'));






INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, CITY, CREATED_DATE)
VALUES (2, 'Priya', 'Mehra', 'priya.mehra@example.com', '9876501234', 'Mumbai', TO_DATE('2023-07-15', 'YYYY-MM-DD'));

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, CITY, CREATED_DATE)
VALUES (3, 'Raj', 'Kapoor', 'raj.kapoor@example.com', '9823456789', 'Bangalore', TO_DATE('2023-08-20', 'YYYY-MM-DD'));

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, CITY, CREATED_DATE)
VALUES (4, 'Sneha', 'Verma', 'sneha.verma@example.com', '9765432109', 'Hyderabad', TO_DATE('2023-09-10', 'YYYY-MM-DD'));

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, CITY, CREATED_DATE)
VALUES (5, 'Rohit', 'Singh', 'rohit.singh@example.com', '9812345670', 'Chennai', TO_DATE('2023-10-05', 'YYYY-MM-DD'));


    commit;

    